PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX db: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbprop: <http://dbpedia.org/property>

select distinct * where {
    ?university rdf:type dbo:University;
                geo:long ?long;
                geo:lat ?lat .
}
